name: covid19model
dependencies:
  - python=3.8 
  - pandas 
  - numpy 
  - pyyaml 
  - pandas 
  - scipy
  - r-abind
  - r-bayesplot
  - r-data.table
  - r-envstats
  - r-caret
  - r-httr
  - r-lubridate
  - r-gdata
  - r-ggpubr
  - r-tidyr
  - r-dplyr
  - r-rstan
  - r-optparse
  - r-abind
  - r-svglite
  - r-jsonlite
  - r-abind
  - r-zoo
  - r-gtable
  - r-ggrepel
  - r-scales
  - r-tidyverse
channels:
  - conda-forge
